version: '3'
services:
  rcon:
    build:
      context: .
      dockerfile: Dockerfile.rcon
    volumes:
      - ./app:/app/app
      - ./keys:/app/keys
      - ./plugins:/app/plugins
      - ./config:/app/config
    tty: true


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/app
    ports:
      - "8500:443"
    depends_on:
      - "rcon"
